### ISSUE TITLE
Can't find the pretraining dataset GiftEvalPretrain in the given link: https://huggingface.co/datasets/Salesforce/GiftEvalPretrain

### ISSUE THREAD

**Issue by mengna-hu** [SalesforceAIResearch/gift-eval#5]

**Comment by liuxu77** [comment]
Hi @mengna-hu, please open the link and click "Files and versions".

**Comment by cuthalionn** [comment]
Hi @mengna-hu, the pretraining data is not accessible publicly yet. It is taking a bit long to upload due to api limits. Hopefully it should be public by next week.

**Comment by cuthalionn** [comment]
Hi @mengna-hu, the pretraining data is public now. 
Thanks for your patience!
